DjangoTest/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', admin.site.urls),
]

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<article_id>[0-9]+)/$', views.get_detail, name='detail'),
    url(r'^create/(?P<article_id>[0-9]+)/$', views.create_or_edit, name='create'),
    url(r'^action_create/$', views.action_create, name='action_create'),

]

polls/urls.py
from django.conf.urls import url
from . import views
app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

blog/models.py
from django.db import models


# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32)
    content = models.TextField()
    pub_data=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField('question', max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return (now - self.pub_date) <= datetime.timedelta(days=1) and self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/views.py
# -*- coding:utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from . import models


def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {"articles": articles})


def get_detail(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_detail.html', {'article': article})


def create_or_edit(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/create.html')
    else:
        article = models.Article.objects.get(pk=article_id)
        return render(request, 'blog/create.html', {'article': article})


def action_create(request):
    title = request.POST.get('title', '标题')
    content = request.POST.get('content', '空白内容')
    article_id = request.POST.get('article_id', '0')
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        return HttpResponseRedirect('/blog')
    else:
        article = models.Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'blog/article_detail.html', {'article': article})

polls/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.utils import timezone

import logging
from .models import Question, Choice

logger = logging.getLogger('polls')


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    logger.info(latest_question_list)
    return render(request, 'polls/index.html', context)


# class IndexView(generic.ListView):
#     template_name = 'polls/index.html'
#     context_object_name = 'latest_question_list'
#
#     def get_queryset(self):
#         return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
#
#
# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'
#
#     def get_queryset(self):
#         return Question.objects.filter(pub_date__lte=timezone.now())
#
#
# class ResultView(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    logger.info(question)
    return render(request, 'polls/detail.html',
                  {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    logger.info(question)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(render, 'polls/detail.html', {'question': p,
                                                    'error_message': "You didn't select a choice"})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

blog/templates/blog/article_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1>{{ article.title }}</h1>

<p>{{ article.content }}</p>

<h3><a href="{% url 'blog:create' article.id %}">修改文章</a></h3>
</body>
</html>

blog/templates/blog/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
<form action="{% url 'blog:action_create' %}" method="post">
    {% csrf_token %}
    {% if article %}
        <input type="hidden" name="article_id" value="{{ article.id }}"/>

        <label>文章标题
            <input type="text" name="title" value="{{ article.title }}"/>
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content" value="{{ article.content }}"/>
        </label>
        <br/>
    {% else %}
        <input type="hidden" name="article_id" value="0"/>
        <label>文章标题
            <input type="text" name="title"/>
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content"/>
        </label>
        <br/>
    {% endif %}
    <input type="submit" value="提交"/>
</form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Templates Title</title>
</head>
<body>
<h1><a href="{% url 'blog:create' 0 %}">创建新文章</a></h1>
{% for article in articles %}
    <a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a>
    <br/>
{% endfor %}

</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    {{ question.question_text }}
</h1>
{#<ui>#}
{#    {% for choice in question.choice_set.all %}#}
{#        <li>{{ choice.choice_text }}</li>#}
{#    {% endfor %}#}
{##}
{#</ui>#}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}--{{ choice.votes }}
            vote{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>